// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hyper_category_test
void hyper_category_test(std::string input, std::string output, int cutoff, std::string root);
RcppExport SEXP FuncBlocks_hyper_category_test(SEXP inputSEXP, SEXP outputSEXP, SEXP cutoffSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input(inputSEXP);
    Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
    Rcpp::traits::input_parameter< int >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< std::string >::type root(rootSEXP);
    hyper_category_test(input, output, cutoff, root);
    return R_NilValue;
END_RCPP
}
// hyper_randset
void hyper_randset(std::string all_genes, int number_of_randomsets, std::string directory, std::string root, std::string mod);
RcppExport SEXP FuncBlocks_hyper_randset(SEXP all_genesSEXP, SEXP number_of_randomsetsSEXP, SEXP directorySEXP, SEXP rootSEXP, SEXP modSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type all_genes(all_genesSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_randomsets(number_of_randomsetsSEXP);
    Rcpp::traits::input_parameter< std::string >::type directory(directorySEXP);
    Rcpp::traits::input_parameter< std::string >::type root(rootSEXP);
    Rcpp::traits::input_parameter< std::string >::type mod(modSEXP);
    hyper_randset(all_genes, number_of_randomsets, directory, root, mod);
    return R_NilValue;
END_RCPP
}
// wilcox_category_test
void wilcox_category_test(std::string input, std::string output, int cut, std::string root);
RcppExport SEXP FuncBlocks_wilcox_category_test(SEXP inputSEXP, SEXP outputSEXP, SEXP cutSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input(inputSEXP);
    Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
    Rcpp::traits::input_parameter< int >::type cut(cutSEXP);
    Rcpp::traits::input_parameter< std::string >::type root(rootSEXP);
    wilcox_category_test(input, output, cut, root);
    return R_NilValue;
END_RCPP
}
// wilcox_randset
void wilcox_randset(std::string nodes_per_gene, int number_of_randomsets, std::string directory, std::string root);
RcppExport SEXP FuncBlocks_wilcox_randset(SEXP nodes_per_geneSEXP, SEXP number_of_randomsetsSEXP, SEXP directorySEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type nodes_per_gene(nodes_per_geneSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_randomsets(number_of_randomsetsSEXP);
    Rcpp::traits::input_parameter< std::string >::type directory(directorySEXP);
    Rcpp::traits::input_parameter< std::string >::type root(rootSEXP);
    wilcox_randset(nodes_per_gene, number_of_randomsets, directory, root);
    return R_NilValue;
END_RCPP
}
