// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hyper_category_test
void hyper_category_test(std::string input, std::string output, int cutoff, std::string root);
RcppExport SEXP FuncBlocks_hyper_category_test(SEXP inputSEXP, SEXP outputSEXP, SEXP cutoffSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type input(inputSEXP);
    Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
    Rcpp::traits::input_parameter< int >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< std::string >::type root(rootSEXP);
    hyper_category_test(input, output, cutoff, root);
    return R_NilValue;
END_RCPP
}
// hyper_randset_blocks
void hyper_randset_blocks(std::string detected, std::string changed, int number_of_randomsets, std::string outfile, std::string term, std::string graph_path, std::string termtoterm, std::string root);
RcppExport SEXP FuncBlocks_hyper_randset_blocks(SEXP detectedSEXP, SEXP changedSEXP, SEXP number_of_randomsetsSEXP, SEXP outfileSEXP, SEXP termSEXP, SEXP graph_pathSEXP, SEXP termtotermSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type detected(detectedSEXP);
    Rcpp::traits::input_parameter< std::string >::type changed(changedSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_randomsets(number_of_randomsetsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outfile(outfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type term(termSEXP);
    Rcpp::traits::input_parameter< std::string >::type graph_path(graph_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type termtoterm(termtotermSEXP);
    Rcpp::traits::input_parameter< std::string >::type root(rootSEXP);
    hyper_randset_blocks(detected, changed, number_of_randomsets, outfile, term, graph_path, termtoterm, root);
    return R_NilValue;
END_RCPP
}
// hyper_randset
void hyper_randset(std::string detected, std::string changed, int number_of_randomsets, std::string outfile, std::string term, std::string graph_path, std::string termtoterm, std::string root);
RcppExport SEXP FuncBlocks_hyper_randset(SEXP detectedSEXP, SEXP changedSEXP, SEXP number_of_randomsetsSEXP, SEXP outfileSEXP, SEXP termSEXP, SEXP graph_pathSEXP, SEXP termtotermSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type detected(detectedSEXP);
    Rcpp::traits::input_parameter< std::string >::type changed(changedSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_randomsets(number_of_randomsetsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outfile(outfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type term(termSEXP);
    Rcpp::traits::input_parameter< std::string >::type graph_path(graph_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type termtoterm(termtotermSEXP);
    Rcpp::traits::input_parameter< std::string >::type root(rootSEXP);
    hyper_randset(detected, changed, number_of_randomsets, outfile, term, graph_path, termtoterm, root);
    return R_NilValue;
END_RCPP
}
// wilcox_category_test
void wilcox_category_test(std::string input, std::string output, int cut, std::string root);
RcppExport SEXP FuncBlocks_wilcox_category_test(SEXP inputSEXP, SEXP outputSEXP, SEXP cutSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type input(inputSEXP);
    Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
    Rcpp::traits::input_parameter< int >::type cut(cutSEXP);
    Rcpp::traits::input_parameter< std::string >::type root(rootSEXP);
    wilcox_category_test(input, output, cut, root);
    return R_NilValue;
END_RCPP
}
// wilcox_randset
void wilcox_randset(std::string nodes_per_gene, std::string gene_scores, int number_of_randomsets, std::string outfile, std::string term, std::string graph_path, std::string termtoterm, std::string root);
RcppExport SEXP FuncBlocks_wilcox_randset(SEXP nodes_per_geneSEXP, SEXP gene_scoresSEXP, SEXP number_of_randomsetsSEXP, SEXP outfileSEXP, SEXP termSEXP, SEXP graph_pathSEXP, SEXP termtotermSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type nodes_per_gene(nodes_per_geneSEXP);
    Rcpp::traits::input_parameter< std::string >::type gene_scores(gene_scoresSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_randomsets(number_of_randomsetsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outfile(outfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type term(termSEXP);
    Rcpp::traits::input_parameter< std::string >::type graph_path(graph_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type termtoterm(termtotermSEXP);
    Rcpp::traits::input_parameter< std::string >::type root(rootSEXP);
    wilcox_randset(nodes_per_gene, gene_scores, number_of_randomsets, outfile, term, graph_path, termtoterm, root);
    return R_NilValue;
END_RCPP
}
