# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyper_category_test <- function(input, output, cutoff, root) {
    invisible(.Call('FuncBlocks_hyper_category_test', PACKAGE = 'FuncBlocks', input, output, cutoff, root))
}

hyper_randset_blocks <- function(detected, changed, number_of_randomsets, outfile, term, graph_path, termtoterm, root) {
    invisible(.Call('FuncBlocks_hyper_randset_blocks', PACKAGE = 'FuncBlocks', detected, changed, number_of_randomsets, outfile, term, graph_path, termtoterm, root))
}

hyper_randset <- function(detected, changed, number_of_randomsets, outfile, term, graph_path, termtoterm, root) {
    invisible(.Call('FuncBlocks_hyper_randset', PACKAGE = 'FuncBlocks', detected, changed, number_of_randomsets, outfile, term, graph_path, termtoterm, root))
}

wilcox_category_test <- function(input, output, cut, root) {
    invisible(.Call('FuncBlocks_wilcox_category_test', PACKAGE = 'FuncBlocks', input, output, cut, root))
}

wilcox_randset <- function(nodes_per_gene, gene_scores, number_of_randomsets, outfile, term, graph_path, termtoterm, root) {
    invisible(.Call('FuncBlocks_wilcox_randset', PACKAGE = 'FuncBlocks', nodes_per_gene, gene_scores, number_of_randomsets, outfile, term, graph_path, termtoterm, root))
}

