# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binom_category_test <- function(directory, cutoff, root, silent) {
    invisible(.Call('FuncBlocks_binom_category_test', PACKAGE = 'FuncBlocks', directory, cutoff, root, silent))
}

binom_randset <- function(nodes_per_gene, number_of_randomsets, directory, root, silent) {
    invisible(.Call('FuncBlocks_binom_randset', PACKAGE = 'FuncBlocks', nodes_per_gene, number_of_randomsets, directory, root, silent))
}

conti_randset <- function(nodes_per_gene, number_of_randomsets, directory, root, silent) {
    invisible(.Call('FuncBlocks_conti_randset', PACKAGE = 'FuncBlocks', nodes_per_gene, number_of_randomsets, directory, root, silent))
}

hyper_category_test <- function(directory, cutoff, root, silent) {
    invisible(.Call('FuncBlocks_hyper_category_test', PACKAGE = 'FuncBlocks', directory, cutoff, root, silent))
}

hyper_randset <- function(nodes_per_gene, number_of_randomsets, directory, root, mod, silent) {
    invisible(.Call('FuncBlocks_hyper_randset', PACKAGE = 'FuncBlocks', nodes_per_gene, number_of_randomsets, directory, root, mod, silent))
}

unlock_environment <- function(env) {
    .Call('FuncBlocks_unlock_environment', PACKAGE = 'FuncBlocks', env)
}

wilcox_category_test <- function(directory, cut, root, silent) {
    invisible(.Call('FuncBlocks_wilcox_category_test', PACKAGE = 'FuncBlocks', directory, cut, root, silent))
}

wilcox_randset <- function(nodes_per_gene, number_of_randomsets, directory, root, silent) {
    invisible(.Call('FuncBlocks_wilcox_randset', PACKAGE = 'FuncBlocks', nodes_per_gene, number_of_randomsets, directory, root, silent))
}

