# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyper_category_test <- function(input, output, cutoff, root) {
    invisible(.Call('FuncBlocks_hyper_category_test', PACKAGE = 'FuncBlocks', input, output, cutoff, root))
}

hyper_randset <- function(all_genes, number_of_randomsets, directory, root, mod) {
    invisible(.Call('FuncBlocks_hyper_randset', PACKAGE = 'FuncBlocks', all_genes, number_of_randomsets, directory, root, mod))
}

wilcox_category_test <- function(input, output, cut, root) {
    invisible(.Call('FuncBlocks_wilcox_category_test', PACKAGE = 'FuncBlocks', input, output, cut, root))
}

wilcox_randset <- function(nodes_per_gene, number_of_randomsets, directory, root) {
    invisible(.Call('FuncBlocks_wilcox_randset', PACKAGE = 'FuncBlocks', nodes_per_gene, number_of_randomsets, directory, root))
}

