# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binom_category_test <- function(directory, cutoff, root, silent) {
    invisible(.Call('GOfuncR_binom_category_test', PACKAGE = 'GOfuncR', directory, cutoff, root, silent))
}

binom_randset <- function(nodes_per_gene, number_of_randomsets, directory, root, silent) {
    invisible(.Call('GOfuncR_binom_randset', PACKAGE = 'GOfuncR', nodes_per_gene, number_of_randomsets, directory, root, silent))
}

conti_category_test <- function(directory, cutoff, root, silent) {
    invisible(.Call('GOfuncR_conti_category_test', PACKAGE = 'GOfuncR', directory, cutoff, root, silent))
}

conti_randset <- function(nodes_per_gene, number_of_randomsets, directory, root, silent) {
    invisible(.Call('GOfuncR_conti_randset', PACKAGE = 'GOfuncR', nodes_per_gene, number_of_randomsets, directory, root, silent))
}

hyper_category_test <- function(directory, cutoff, root, silent) {
    invisible(.Call('GOfuncR_hyper_category_test', PACKAGE = 'GOfuncR', directory, cutoff, root, silent))
}

hyper_randset <- function(nodes_per_gene, number_of_randomsets, directory, root, mod, silent) {
    invisible(.Call('GOfuncR_hyper_randset', PACKAGE = 'GOfuncR', nodes_per_gene, number_of_randomsets, directory, root, mod, silent))
}

unlock_environment <- function(env) {
    .Call('GOfuncR_unlock_environment', PACKAGE = 'GOfuncR', env)
}

wilcox_category_test <- function(directory, cut, root, silent) {
    invisible(.Call('GOfuncR_wilcox_category_test', PACKAGE = 'GOfuncR', directory, cut, root, silent))
}

wilcox_randset <- function(nodes_per_gene, number_of_randomsets, directory, root, silent) {
    invisible(.Call('GOfuncR_wilcox_randset', PACKAGE = 'GOfuncR', nodes_per_gene, number_of_randomsets, directory, root, silent))
}

